### ISSUE TITLE
Build project translations

### ISSUE THREAD

**Issue by snowtema** [crowdin/crowdin-ruby-client-v1#8]
REST API v2 has a [method](https://support.crowdin.com/api/v2/#operation/api.projects.translations.builds.build) to build translations. Is this feature planning to add in a gem?

**Comment by andrii-bodnar** [comment]
@snowtema 
Thanks a lot, that's a great idea! We also have been thinking of that and definitely add it to our list of future improvements.

**Comment by cmrd-senya** [comment]
Will be fixed by #10
